feat: Implement Testimonials Section on Homepage #59
Tanay-ErrorCode/lupo-skill pull request #119
Opened 2024-05-25 22:28 UTC by nishant0708

feat: Implement Testimonials Section on Homepage #59

#59

-Added testimonial section in homepage
-Responsive as well

https://github.com/Tanay-ErrorCode/lupo-skill/assets/101548649/412b708d-ceff-4d78-9179-467151a6b5bc

2024-05-26 06:07 UTC, Doraemon012 commented on src/components/testimonial/testimonial.css
> +  transform: translateY(4rem);
Increase little bit gap between the indicators.

2024-05-26 06:07 UTC, Doraemon012 commented on src/components/testimonial/TestimonialCard.jsx
> +            <Typography variant="h5" fontSize={isSmallScreen ? "20px" : "24px"} fontWeight="700" whiteSpace="nowrap">
Do not give the font size in `px`, instead use `rem`.

2024-05-26 06:07 UTC, Doraemon012 commented on src/components/HomePage/HomePage.tsx
> +              <h1 className="happy">Happy Users</h1>
Make this bold.

2024-05-26 06:08 UTC, Doraemon012 requested changes
Please make the requested changes

2024-05-26 06:09 UTC, Doraemon012 commented
@nishant0708
1. On **tablet screens, 2 cards** should be visible, **1 on phone**.
2. The component should be defined in a `tsx` file instead of `jsx`
3. Remove the added image
4. Use this sample data:
``` tsx
const testimonials = [
  {
    name: 'Elena Rodriguez',
    text: "I can't express enough how much I appreciate this platform. The live events are incredibly engaging, and the articles provide valuable insights. I've learned so much, and it's all thanks to this website!",
    image: 'https://randomuser.me/api/portraits/women/9.jpg',
  },
  {
    name: 'Michael Chang',
    text: "As a busy professional, I struggle to find time for skill development. This website has been a lifesaver! The resources are concise yet comprehensive, and the live events fit perfectly into my schedule. Highly recommended for anyone looking to grow professionally.",
    image: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    name: 'Sophia Patel',
    text: "I stumbled upon this website while searching for ways to enhance my creative skills. It's been a revelation! The variety of topics covered is impressive, and I've found the live events to be both informative and inspiring. Thank you for creating such a valuable resource!",
    image: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    name: 'David Thompson',
    text: "I've been a part of many skill-sharing platforms, but none compare to this one. The community here is supportive, the content is top-notch, and the live events feel like attending a masterclass. Kudos to the team behind this fantastic initiative!",
    image: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    name: 'Emma Johnson',
    text: "This website has reignited my passion for learning! The articles are well-written and insightful, and the live events provide a unique opportunity to interact with industry experts. I've already recommended it to all my friends!",
    image: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    name: 'Jonathan Lee',
    text: "I've always believed in the power of continuous learning, and this website has made it incredibly easy for me to pursue that belief. From workshops to webinars, there's something for everyone here. It's become my go-to platform for skill development!",
    image: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
  {
    name: 'Maria Sanchez',
    text: "I'm amazed by the quality of content available on this platform. Whether you're a beginner or an expert, there's always something new to learn. The live events are particularly impressive, with knowledgeable speakers sharing valuable insights. I couldn't be happier with my experience!",
    image: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    name: 'Chris Wilson',
    text: "I've been using this website for a few months now, and it's exceeded all my expectations. The resources are comprehensive, the articles are well-researched, and the live events are nothing short of brilliant. It's like having a personal mentor at your fingertips!",
    image: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
];
```

2024-05-26 07:13 UTC, nishant0708 commented
Hey in small screen then will I have to increase number of indicator??

2024-05-26 08:05 UTC, Doraemon012 commented
> Hey in small screen then will I have to increase number of indicator??

@nishant0708 Yes

2024-05-26 11:09 UTC, nishant0708 commented
@Doraemon012  please check these changes ..and tell me if any changes require

2024-05-27 14:21 UTC, Tanay-ErrorCode commented
@nishant0708 Please add sliding animation to the carousel.

2024-05-30 05:20 UTC, nishant0708 commented
@Tanay-ErrorCode @Doraemon012  please tell me changes required??

2024-05-30 05:50 UTC, Doraemon012 commented
@nishant0708 

Please increase the margin between two cards (on small devices)

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/f572e2f0-21e5-4494-bced-613c8eb549c1)

</br>
The height of all cards should be same. Also, remove the inconsistency in margins between cards.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/239451f9-ba85-4eab-b184-10910622b8d4)

2024-05-30 08:51 UTC, nishant0708 commented
hey @Doraemon012 I tried but when i try to maintain same height of all the card the content is overflowing and when i try to fix overflowing issure the card heights get different so can you tell me or give a idea what can i do for that

2024-05-30 09:56 UTC, nishant0708 commented
Hey @Doraemon012  @Tanay-ErrorCode  please check this Latest commit. It Will Work Fine Now

2024-05-30 10:34 UTC, Doraemon012 approved these changes
@nishant0708 Great work !

2024-05-30 16:47 UTC, Tanay-ErrorCode commented
@nishant0708 Good work!

2024-05-30 16:47 UTC, merged