Feat: #118 : Redesigned the Navbar component utilizing MUI
Tanay-ErrorCode/lupo-skill pull request #127
Opened 2024-05-26 18:41 UTC by Utsavladia

**What kind of change does this PR introduce?**

Redesigned the Navbar component as provided in the Figma

 utilizing Material-UI and CSS for styling 
**Issue Number:**

Fixes #118 
**Snapshots/Videos:**

![Screenshot 2024-05-27 000052](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/35e670d6-2343-4345-af08-d20e7b3eaba6)
![Screenshot 2024-05-26 234016](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/f201ddc2-b149-4658-9caf-10a993a33473)

**Other information**

I made it Responsive for best user experience..
Thank you for giving me this opportunity.

2024-05-26 19:19 UTC, Doraemon012 commented
@Utsavladia 

  - It was mentioned in the issue that the navbar has different design for the home screen, and the other pages.

  - Navbar for **Home Screen**:
  
  ![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/b6ed4fb0-ad2d-43e3-9d87-83d9d17b0387)
  
 -  Navbar for **other pages**:
  
  ![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/e0aab28f-33d1-4266-911a-0b5c02349e97)
  
  - Also, the link to figma designs was provided so that the designs can be viewed there.
  - The the navbar should be adjustable (through props) for the two designs (for home page and for other pages)
  - Please use the colors for buttons, from `theme.tsx`
  - In addition to the colors in `theme.tsx` use these colors for the `Home Page Navbar`
  
    ```css
    home-nav-background: 'rgba(255, 255, 255, 0.17)', // ffffff with 17% opacity
    home-nav-inactiveButton: 'rgba(252, 252, 252, 0.20)', // fcfcfc with 20% opacity
    ```

2024-05-26 19:32 UTC, Doraemon012 commented on src/components/Cards/CreateEvent/CreateEvent.tsx
> +          variant="contained"
Why have you changed these buttons ?
Please revert this.

2024-05-26 19:33 UTC, Doraemon012 commented on src/components/Cards/CreateEvent/CreateEvent.tsx
> -          <Button variant="secondary" onClick={handleClose}>
Why have you changed these buttons ?
Please revert this.

2024-05-26 19:34 UTC, Doraemon012 requested changes
Please make the requested changes.

2024-05-27 02:46 UTC, Utsavladia commented
> Please make the requested changes.

Thank you for the feedback, I will try to fix it.

2024-06-05 13:32 UTC, closed without merging