Redesigned the Event card
Tanay-ErrorCode/lupo-skill pull request #158
Opened 2024-06-01 09:26 UTC by Utsavladia

**What kind of change does this PR introduce?**

Redesigned the Event card according to the design provided in Figma.

**Issue Number:**

Fixes #113 
**Snapshots/Videos:**

![Screenshot 2024-06-01 144316](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/9dcd81ac-86ee-4c4e-b77e-01aa6acf4e6a)

**Other information**

2024-06-01 13:50 UTC, Tanay-ErrorCode commented
@Utsavladia Please share a full screen video of the functionality.

2024-06-01 14:27 UTC, Utsavladia commented
Here is the illustration of redesigned card.
Uploading cardillustration recording (1).mp4…

2024-06-01 14:28 UTC, Utsavladia commented
Here is the video of redesigned Event card.

https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/97a3f8b7-954a-40f4-bba6-9c0d08946163

2024-06-01 14:41 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                    fontSize: "16px",
Update this using `theme.tsx`. Remember that never use `px` for font sizes, user `rem` instead. This helps keeping the webpage responsive.

2024-06-01 14:41 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                style={{ fontSize: "26px", color: theme.colors.primary }}
Use the font size `textBody` frm `theme.tsx`.

2024-06-01 14:44 UTC, Doraemon012 commented
@Utsavladia 
1. The description should cover max 3 lines, if it is more than that then it should be truncated by `...` Like this:
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/ab5015b1-5117-481f-8391-db74a552fd56)

2. The heights of all cards needs to be same.
3. Remove `Indian Standard Time` from the event time.

2024-06-01 14:45 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +              <span
Use the [MUI Chip Component](https://mui.com/material-ui/react-chip/#clickable)

2024-06-01 14:46 UTC, Doraemon012 requested changes
Please make the requested changes

2024-06-01 16:04 UTC, Tanay-ErrorCode commented
@Utsavladia kindly fix  height of the cards are not equal.

![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/90561803/e67a69bb-74c4-46fa-a6d7-a81fd72187ba)

2024-06-01 16:55 UTC, Utsavladia commented
Sure, Thank you for the review I will try to fix all...

2024-06-01 18:03 UTC, Utsavladia commented
Here is the video after suggested changes


https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/b0ea6a49-b9ee-4619-9377-031a9a4db5a6

2024-06-02 13:41 UTC, Doraemon012 commented
@Utsavladia The same card design should be applied for Dashboard and User Profile.

2024-06-02 13:53 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                <Chip
Make this clickable. [https://mui.com/material-ui/react-chip/#clickable](https://mui.com/material-ui/react-chip/#clickable)

2024-06-02 13:57 UTC, Doraemon012 commented
- Dashboard cards should be clickable.
- The card title should be max 2 lines, if more than that then it should be truncated by `...`

2024-06-02 13:57 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                  sx={{ backgroundColor: theme.colors.secondaryLight }}
Make the font bold

2024-06-02 14:00 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                      padding: "6px 12px",
make the padding `2px 12px`

2024-06-02 17:29 UTC, Utsavladia commented
Done all the suggested changes

Profile cards
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/d1677b9c-4b73-4000-bf45-cfb7eb6adf26)

Dashboard cards
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/08477808-bdb2-48c6-be18-a3c1c8c718a6)

clickable links and fixed padding.
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/36bacd86-88a8-4636-9c82-8a0f7aa3db2b)

2024-06-15 05:10 UTC, Utsavladia commented
@Doraemon012  
I have resolved the conflicts and please let me know if changes required.
And kindly merge this after review else conflicts will keep coming...

2024-06-15 12:43 UTC, Tanay-ErrorCode commented
@Utsavladia Please provide a video of the output. And please do not resolve merge conflicts on your own.

2024-06-15 13:06 UTC, Utsavladia commented
sure @Tanay-ErrorCode 
Please find the video of output below..


https://github.com/Tanay-ErrorCode/lupo-skill/assets/124615886/e357c957-f974-46d7-bb2f-9005b2c19678

2024-06-15 13:10 UTC, Tanay-ErrorCode commented
@Utsavladia Is this the video of the [latest commit ](https://github.com/Tanay-ErrorCode/lupo-skill/pull/158/commits/573af8424e70f4083d5e894b8c4e7fbf8956dac5)?

2024-06-15 13:13 UTC, Utsavladia commented
@Tanay-ErrorCode 
yes this is the video of latest commit before merging the main or resolving the conflicts.

2024-06-15 13:15 UTC, Tanay-ErrorCode commented
> @Tanay-ErrorCode yes this is the video of latest commit before merging the main or resolving the conflicts.

@Utsavladia I want the video after resolving merge conflicts. Please pull the latest commit changes.

2024-06-15 14:10 UTC, Utsavladia commented
@Tanay-ErrorCode 
You are right i should not have resolved the conflict without asking.
It gave too many errors.
I have reverted to the last working commit that i mad.
The video above I attached is the video of that last commit.

2024-06-22 17:35 UTC, Doraemon012 approved these changes

2024-06-22 17:35 UTC, merged