[Feature] : Navbar mobile site changed
Tanay-ErrorCode/lupo-skill pull request #265
Opened 2024-06-24 04:07 UTC by sivaprasath2004

Hello @Tanay-ErrorCode ,
**What kind of change does this PR introduce?**

[Feature] : Navbar mobile site  

**Issue Number:**

Fixes #258 
**Snapshots/Videos:**

### Before

 
![Screenshot from 2024-06-23 08-27-48](https://github.com/Tanay-ErrorCode/lupo-skill/assets/121082414/d69a0ac7-90dd-4f18-b432-0b8da9b814be)

### After

[Screencast from 2024-06-24 09-31-35.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/121082414/300e2877-14f7-4542-9334-8aa5b01c99cc)

2024-06-24 05:28 UTC, Doraemon012 commented on src/firebaseConf.ts
> -import {
Why did you delete this file ?

2024-06-24 05:28 UTC, Doraemon012 commented on src/components/NavBar/NavBar.tsx
> +                      backgroundColor: "#0F0F0F",
Use the colors from `App.css` or `Theme.tsx`. Do not hard code the values.

2024-06-24 05:28 UTC, Doraemon012 commented on src/components/NavBar/NavBar.tsx
> +                  anchor="top"
> anchor="top"
It should be right.

2024-06-24 05:30 UTC, Doraemon012 commented on src/components/NavBar/NavBar.tsx
> +                Drawer Lupo Skill
Why did you add this ?

2024-06-24 05:30 UTC, Doraemon012 commented
@sivaprasath2004 
Do not add icons.

2024-06-24 05:31 UTC, Doraemon012 requested changes
Make the requested changes.

2024-06-24 06:02 UTC, sivaprasath2004 commented
@Doraemon012 please check

2024-06-26 18:22 UTC, Tanay-ErrorCode commented
@sivaprasath2004 Any updates?

2024-06-27 04:16 UTC, sivaprasath2004 commented
[Screencast from 2024-06-27 09-44-30.webm](https://github.com/Tanay-ErrorCode/lupo-skill/assets/121082414/dfff5bf9-5174-4bad-97ec-5fe1ec4fed90)

Hello @Tanay-ErrorCode , i will changed it.

2024-06-28 17:57 UTC, Doraemon012 approved these changes

2024-06-29 09:38 UTC, merged

2024-06-29 09:38 UTC, Tanay-ErrorCode commented
@sivaprasath2004 Good work.