feat: want to write backend Of comment section of blogs page #369
Tanay-ErrorCode/lupo-skill pull request #370
Opened 2024-07-30 16:51 UTC by nishant0708

**What kind of change does this PR introduce?**

![Screenshot 2024-07-30 221940](https://github.com/user-attachments/assets/3903d8af-aa4d-4b00-8620-60dce8fff041)

**Issue Number:**

Fixes #369 
**Snapshots/Videos:**

**Other information**

2024-07-30 16:53 UTC, nishant0708 commented
hey @Tanay-ErrorCode  @Doraemon012  please review this whenever possible

2024-07-31 17:08 UTC, Tanay-ErrorCode commented
@nishant0708 Can you convert this to non-modal one? Down the article, the comments should be shown.

2024-07-31 17:10 UTC, nishant0708 commented
Yes I guess @Tanay-ErrorCode . Same ui just below content naa.?

2024-07-31 17:11 UTC, Tanay-ErrorCode commented
@nishant0708 Yes.

2024-07-31 17:12 UTC, nishant0708 commented
@Tanay-ErrorCode okay both pr changes will be done by tomorrow

2024-08-01 01:33 UTC, nishant0708 commented
![image](https://github.com/user-attachments/assets/4fe8f8e5-3b53-4099-9739-eee4d628948b)
hey @Tanay-ErrorCode done . let me know any further change if required

2024-08-01 17:06 UTC, Doraemon012 commented on src/components/Article/DiscussionModal.tsx
> +      const commentRef = ref(db, `comments/${newCommentId}`);
@nishant0708 The comments node must be inside the single article and it should only contain the comments for that article only.

* articles
  * {an_article}
    * {content...}
    * comments

2024-08-01 17:06 UTC, Doraemon012 requested changes
@nishant0708 Please make the required changes.

2024-08-01 17:17 UTC, nishant0708 commented
hey @Doraemon012 i did that only in start but it was throwing a lot of error
![Screenshot 2024-07-30 220110](https://github.com/user-attachments/assets/930c0d25-5ca8-45b1-8bd6-8d35b6f6c014)
see . so Did Normatilazation of Comments

2024-08-02 14:51 UTC, nishant0708 commented
hey @Tanay-ErrorCode @Doraemon012  fixed this 

![Screenshot 2024-08-02 202011](https://github.com/user-attachments/assets/07c54c11-ad2e-4799-bd5d-7446703930bc)

2024-08-02 17:13 UTC, Doraemon012 approved these changes

2024-08-02 17:13 UTC, merged