modifies event cards
Tanay-ErrorCode/lupo-skill pull request #67
Opened 2024-05-18 11:28 UTC by Rohitha-pudu

#22 closes
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116823590/a24a96e0-c309-4387-9510-bfe508a67da2)

2024-05-18 13:15 UTC, Doraemon012 commented
@Rohitha-pudu The UI of the cards does not match the designs provided in the Figma file. The theme colors, border radii, etc., are already defined in the 'theme.tsx' file. Please ensure that the card UI matches the Figma design as closely as possible.

I have added the link to the [Figma design](https://www.figma.com/file/ce7ZISlm3vCEGIADOZt0Ma/LUPO-SKILL?type=design&node-id=0%3A1&mode=design&t=4OZ414vJtGAwoVvH-1) in the issue itself. Here's how you can see the exact colors and values, such as border radius, in Figma:

https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/c1fe8e14-50af-46b6-b473-5dbeecbe3748

There is no need to write hard-coded values as they are already defined in `theme.tsx`.

Also, do not use `px`; instead, use the corresponding `rem`, `vw`, and `vh` units to make the UI responsive.

Here are some useful articles:
- [CSS Units: When to Use Each One](https://www.freecodecamp.org/news/css-units-when-to-use-each-one/)
- [Responsive Web Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)

You can use [MUI](https://mui.com/material-ui/all-components/), [React Bootstrap](https://react-bootstrap.netlify.app/), and CSS. Also, note that you can customize and use components like [Chips](https://mui.com/material-ui/react-chip/) that are already defined in styling libraries like MUI.

2024-05-19 10:03 UTC, Rohitha-pudu commented
![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116823590/4571cbfb-5b6d-4313-827e-2f2c40c0dcc5)
is it okay?

2024-05-19 10:37 UTC, Doraemon012 commented
@Rohitha-pudu Looks good.
Just remove the `Indian Standard Time`, reduce the padding inside the host name container, and the tags. Also make the color of card footer same as the card body.

2024-05-19 11:11 UTC, Rohitha-pudu commented
> @Rohitha-pudu Looks good. Just remove the `Indian Standard Time`, reduce the padding inside the host name container, and the tags. Also make the color of card footer same as the card body.

done

2024-05-19 12:38 UTC, Doraemon012 commented on .gitignore
> +src/firebaseConf.ts
Why did you add this to `.gitignore` ?
You were not supposed to do this.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.css
> +  margin-top: 14px;
You were told to make the component responsive. I asked you to use em, rem, etc.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.css
> +    rgb(255, 255, 255) 90%
In the comment, I told you to use the colors and values from `theme.tsx`. This will help us to keep the theme consistent.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                  borderTopRightRadius: "1rem",
Please remember that whenever you are setting border radius, keep it in px.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                  <div className="py-2">
You should use this [MUI Chip](https://mui.com/material-ui/react-chip/)

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                        backgroundColor: "#0DCAF080",
You were supposed to use colors form theme.tsx and not hardcode them.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                          style={{ fontSize: "13px" }}
Use rem.

2024-05-19 12:49 UTC, Doraemon012 commented on src/components/Cards/EventCard/EventCard.tsx
> +                  borderRadius: "1rem",
There was no border radius for this in the figma designs.

2024-05-19 12:50 UTC, Doraemon012 commented on src/components/EventDetails/EventDetails.tsx
> +        setTags(eventData.tags.split(" "));
The tags are be split by `,`.

2024-05-19 12:52 UTC, Doraemon012 requested changes
Make the requested changes.

2024-05-19 12:54 UTC, Doraemon012 commented
@Rohitha-pudu 

- Please update your branch, it has been outdated.
    
    This happens when you have pushed commits to your branch and the remote repo has also been updated. That's why, it shows something like `your branch is 1 commit behind and 3 commits ahead of...`
    
    To resolve this, go to your branch, then click on `Sync Fork` and then click on `Update branch`.
    
    You can use the below screen shot and recording as reference. Here, the branch `patch-1` is one commit ahead and 9 commits behind of the remote repository.
    
    ![image](https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/a7cd05a7-f482-4417-a0f3-e5f5875f6743)
    
    https://github.com/Tanay-ErrorCode/lupo-skill/assets/116624667/6fe638ca-bc95-4a5e-a43a-11d7757f21dd

2024-05-19 15:40 UTC, closed without merging